# Generated by Django 4.2.9 on 2024-09-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_projectset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='original_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.project'),
        ),
    ]
