# Generated by Django 4.2.9 on 2024-09-10 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_project_original_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('project_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='infrastructure.projectset')),
            ],
        ),
    ]
