# Generated by Django 4.2.9 on 2024-09-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_projectsetlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetLinkAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('project_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.projectset')),
            ],
        ),
    ]
