# Generated by Django 4.2.9 on 2024-09-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_projectsetlinkaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsetlink',
            name='project_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='infrastructure.projectset'),
        ),
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.projectset')),
            ],
        ),
    ]
