# Generated by Django 4.2.9 on 2024-09-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_remove_projectsetlinkaccess_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsetlinkaccess',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
