# Generated by Django 4.2.9 on 2024-09-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_projectset_download_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(max_length=50)),
                ('filter_value', models.CharField(max_length=255)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('filter_type', 'filter_value')},
            },
        ),
    ]
