# Generated by Django 4.2.9 on 2024-08-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_linkedin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
